### PR TITLE
gdp small batch file imported.

### PR DESCRIPTION
**Pull request by AlbertLee125**
I added the small batch problem from the dsda-gdp. I only added the code so that Zedong can test the code.

### CODE REVIEW

**Comment by bernalde** [comment]
What's the difference between this and #10 ?

**Comment by AlbertLee125** [comment]
I just developed the branch just for Zedong and I to test the LDSDA. There are no difference with PR #10.

**Comment by bernalde** [comment]
The action shows that black hasn't been run. You can go into the link to see the details, where it shows that gdp_small_batch.py hasn't been run though black

**Comment by bernalde** [comment]
As long as the tests don't pass, no review will be done on this PR. This applies to all the other PRs.
Try running the test locally to see if it passes first.

**Comment by AlbertLee125** [comment]
This is redundant with #10. I will remove this PR.

**Pull request closed without merging**
