### PR TITLE
Refactor and update heat integration models

### PR DESCRIPTION
**Pull request by AlbertLee125**
This pull request includes several commits that refactor and update the heat integration models. The changes include reforming the documentation, setting up parameter documentation, updating the models to account for Pyomo logical expression system and Boolean indicator_vars, and improving code readability. These changes aim to enhance the functionality and maintainability of the heat integration models.

### CODE REVIEW

**Review by bernalde — CHANGES_REQUESTED** [review]
Well done!
I didn't notice if there was a statement at the beginning of the files adding the reference from where these models are coming from. If there is, please just answer this and I will merge it.

**Comment by ZedongPeng** [comment]
I find the following header.
```
"""Cafaro approximation parameter estimation.
 Rather than use the cost relation (1), Cafaro & Grossmann, 2014 (DOI:
 https://doi.org/10.1016/j.compchemeng.2013.10.001) proposes using (2), which has much better
 behaved derivative values near x=0. However, we need to use parameter
 estimation in order to derive the correct values of k and b.
This file performs the parameter estimation.
(1) cost = factor * (area) ^ 0.6
(2) cost = factor * k * ln(bx + 1)
"""
```

**Review by AlbertLee125 — COMMENTED** [review]
The way that the heat exchanger work is done like import the common parts of the model from the common.py and modify the code using conventional.py modular_discrete.py modular_discrete_single.py modular_integer.py. I add the name of the model by adding the name on the m=ConcreteModel('name'). However, I am facing challenge for naming.  What is the best way to give them separate names for model with different cases?

The header is already on the top on common conventional. Cafaro approximation is a function for approximating the parameters. So I did not as much docuementation to other functions.

**Review by bernalde — APPROVED** [review]
Please add the header for the general file. For the benchmarking we need to consider each case independently @ZedongPeng 
Merging contingent on @ZedongPeng and @tristantc approval

**Review by AlbertLee125 — COMMENTED** [review]
I added the header for the general file, common.py.

**Pull request merged**
